config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from users.views import index

urlpatterns = [
    path('', index, name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('inventories/', include('inventories.urls')),
    path('items/', include('items.urls')),
    path('users/', include('users.urls')),
]

# Static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

# Media files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''
inventory-manager/ -> Home Site
inventory-manager/<username>/ -> User Page (displays user stats)
inventory-manager/<username>/inventory/ -> List of inventory groups and stats about each
inventory-manager/<username>/inventory/<InventoryGroup>/ -> List of items inside InventoryGroup with stats about each
inventory-manager/<username>/items/ -> List of all items in all inventory groups
inventory-manager/<username>/inventory/items/<ItemId>/ -> Detail about single item
'''

inventories/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.InventoryListView.as_view(), name='inventories'),
    #path('<uuid:pk>/', views.InventoryDetailView.as_view(), name='inventory-detail'),
    #path('<uuid:pk>/', views.inventory_detail_view, name='inventory-detail'),
    #path('groups/<uuid:pk>', views.InventoryGroupDetailView.as_view(), name='inventorygroup-detail'),
]

items/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ItemListView.as_view(), name='items'),
    path('create/', views.ItemCreate.as_view(), name='item-create'),
    #path('<uuid:pk>/', views.ItemDetailView.as_view(), name='item-detail'),
    path('<uuid:pk>/update/', views.ItemUpdate.as_view(), name='item-update'),
    path('<uuid:pk>/delete/', views.ItemDelete.as_view(), name='item-delete'),
]

inventories/models.py
import uuid
from django.conf import settings
from django.db import models
from django.urls import reverse

class Inventory(models.Model):
    # Fields
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, unique=True, help_text='Enter user that owns the inventory (required).')

    # Metadata

    class Meta:
        ordering = ['user__username',]

    # Methods

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        #return reverse('inventory-detail', args=[str(self.id)])
        return reverse('inventory-detail', kwargs={'username': self.user.username})
    
    def user_has_permission(self, user):
        '''Returns True if user has permission to view Inventory instance.'''
        return self.user == user

class InventoryGroup(models.Model):
     # Fields

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE, help_text='Enter inventory that the inventory group belongs to (required).')
    items = models.ManyToManyField('items.Item', blank=True, help_text='Enter items that belong in the inventory group.')
    name = models.CharField(max_length=50, blank=True, help_text='Enter name of the inventory group.')
    #slug = models.SlugField(max_length=50, unique=True, null=False, help_text='Enter a url-safe, unique, lower-case version of the inventory group.')
    last_modified = models.DateTimeField(auto_now=True)

    # Metadata

    class Meta:
        ordering = ['name', '-last_modified']

    # Methods

    def __str__(self):
        return f'{self.inventory.user} ({self.name})'

    def get_absolute_url(self):
        #return reverse('inventorygroup-detail', args=[str(self.id)])
        return reverse('inventorygroup-detail', kwargs={'pk': str(self.id), 'username': self.inventory.user.username})

inventories/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Inventory, InventoryGroup

class InventoryListView(LoginRequiredMixin, generic.ListView):
    model = Inventory
    paginate_by = 25

class InventoryDetailView(LoginRequiredMixin, generic.DetailView):
    model = Inventory

@login_required
def inventory_detail_view_old(request, pk):
    inventory = get_object_or_404(Inventory, pk=pk)

    # Check if user has access to inventory
    if request.user != inventory.user:
        raise PermissionDenied

    context = {
        'inventory': inventory,
    }

    return render(request, 'inventories/inventory_detail.html', context=context)

@login_required
def inventory_detail_view(request, username):
    user = get_object_or_404(get_user_model(), username=username)    
    inventory = get_object_or_404(Inventory, user=user)

    # Check if user making request has access to inventory
    if not inventory.user_has_permission(request.user):
        raise PermissionDenied

    context = {
        'inventory': inventory,
    }

    return render(request, 'inventories/inventory_detail.html', context=context)

class InventoryGroupDetailView(LoginRequiredMixin, generic.DetailView):
    model = InventoryGroup

@login_required
def inventorygroup_detail_view_old(request, pk):
    inventorygroup = get_object_or_404(InventoryGroup, pk=pk)

    context = {
        inventorygroup,
    }

    return render(request, 'inventories/inventorygroup_detail.html', context=context)

@login_required
def inventorygroup_detail_view(request, pk, username):
    user = get_object_or_404(get_user_model(), username=username)
    inventorygroup = get_object_or_404(InventoryGroup, pk=pk)

    # Check that inventorygroup instance has matching user
    if inventorygroup.inventory.user != user:
        raise PermissionDenied

    # Check if user making request has access to inventory
    if not inventorygroup.inventory.user_has_permission(request.user):
        raise PermissionDenied

    context = {
        'inventorygroup': inventorygroup,
    }

    return render(request, 'inventories/inventorygroup_detail.html', context=context)

inventories/templates/inventories/inventory_detail.html
{% extends "base_generic.html" %}

{% block title %}Inventory Detail {{ inventory.id }}{% endblock %}

{% block content %}
    <h1>{{ inventory.user }}'s Inventory</h1>

    <p><strong>ID:</strong> {{ inventory.id }}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Inventory Groups</h4>

        {% for inventorygroup in inventory.inventorygroup_set.all %}
            <hr>
            <a href="{{ inventorygroup.get_absolute_url }}">{{ inventorygroup.name }}</a>
        {% endfor %}
    </div>
{% endblock %}

inventories/templates/inventories/inventory_list.html
{% extends "base_generic.html" %}

{% block title %}Inventory List View{% endblock %}

{% block content %}
    <h1>Inventory List View</h1>

    {% if inventory_list %}
        <ul>
            {% for inventory in inventory_list %}
                <li>
                    <a href="{{ inventory.get_absolute_url }}">{{ inventory }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are NO inventories!</p>
    {% endif %}
{% endblock %}

inventories/templates/inventories/inventorygroup_detail.html
{% extends "base_generic.html" %}

{% block title %}Inventory Group Detail {{ inventorygroup.id }}{% endblock %}

{% block content %}
    <h1>{{ inventorygroup.inventory.user }}'s Inventory of {{ inventorygroup.name }}</h1>

    <p><strong>ID:</strong> {{ inventorygroup.id }}</p>

    <h2>Items:</h2>

    {% if inventorygroup.items %}
        <ul>
            {% for item in inventorygroup.items.all %}
                <li>
                    <a href="{{ item.get_absolute_url }}">{{ item }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>There are NO items in this inventory group!</p>
    {% endif %}
{% endblock %}